language: go
go:
  - 1.4
  - 1.3
  - release
  - tip
before_install:
  - go get github.com/tj/go-debug
  - go get gopkg.in/resilient-http/resilient.go.v0
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - make test
